### PR TITLE
fix: openapi validation errors

### PR DESCRIPTION
**Pull request by npwork**
There are many openapi issues at the moment (which affect codegen plugins)
I've fixed part that is available for the opensource

Please check openapi validation errors that are in your internal modules
https://app.swaggerhub.com/apis/npworkorg/tatum-api/3.8.8

Screenshot 2021-12-08 at 17 47 22

### CODE REVIEW

**Comment by samuelsramko** [comment]
That's because we process this OpenAPI files internally in our master scheme. If you want to generate OpenAPI clients, use the OpenAPI provided here on top - https://tatum.io/apidoc.php

**Comment by npwork** [comment]
You are right. 
The screenshot that I've attached above is actually from https://tatum.io/apidoc.php schema.

I know this fix won't change your main schema, just wanted to point that there are openapi validation errors in your main schema as well.

**Comment by samuelsramko** [comment]
Thanks for that, We will solve that asap.

**Comment by npwork** [comment]
@samuelsramko  I've created diff with fixes that needs to be done.
https://github.com/npwork/tatum-openapi/pull/1

Hope this will help :)

**Pull request closed without merging**
